AppBundle\Entity\Image:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        url:
            type: string
            length: 255
        imageType:
          type: string
          columnDefinition: ENUM('icon', 'medium', 'screen', 'small', 'super', 'thumb', 'tiny')
    manyToOne:
        game:
          targetEntity: Game
          inversedBy: images
          joinColumn:
            name: game_id
            referencedColumnName: id

    lifecycleCallbacks: {  }
